/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from src to dst, ignoring pointers.
 * Note that only PWork are supposed to be pointers within a DWork structure
 * and that sub-structures are copied in one operation since they do not contain pointers.
 */
int OpalSnapshot_Copy_DWork(void * src, void * dst) {
   D_Work * pSrc = (D_Work*)src;
   D_Work * pDst = (D_Work*)dst;
   int size = 0, eltSize = 0;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE, &pSrc->DiscreteTimeIntegrator_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Currentfilter_states);
   memcpy(&pDst->Currentfilter_states, &pSrc->Currentfilter_states, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->inti_DSTATE);
   memcpy(&pDst->inti_DSTATE, &pSrc->inti_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_n);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_n, &pSrc->DiscreteTimeIntegrator_DSTATE_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Delay_DSTATE);
   memcpy(&pDst->Delay_DSTATE, &pSrc->Delay_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE);
   memcpy(&pDst->UnitDelay1_DSTATE, &pSrc->UnitDelay1_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_p);
   memcpy(&pDst->UnitDelay1_DSTATE_p, &pSrc->UnitDelay1_DSTATE_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE);
   memcpy(&pDst->UnitDelay_DSTATE, &pSrc->UnitDelay_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_k);
   memcpy(&pDst->UnitDelay_DSTATE_k, &pSrc->UnitDelay_DSTATE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_a);
   memcpy(&pDst->UnitDelay_DSTATE_a, &pSrc->UnitDelay_DSTATE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE);
   memcpy(&pDst->SFunction_DSTATE, &pSrc->SFunction_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_o);
   memcpy(&pDst->SFunction_DSTATE_o, &pSrc->SFunction_DSTATE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_g);
   memcpy(&pDst->SFunction_DSTATE_g, &pSrc->SFunction_DSTATE_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_b);
   memcpy(&pDst->SFunction_DSTATE_b, &pSrc->SFunction_DSTATE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_l);
   memcpy(&pDst->SFunction_DSTATE_l, &pSrc->SFunction_DSTATE_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_c);
   memcpy(&pDst->SFunction_DSTATE_c, &pSrc->SFunction_DSTATE_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_os);
   memcpy(&pDst->SFunction_DSTATE_os, &pSrc->SFunction_DSTATE_os, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_h);
   memcpy(&pDst->SFunction_DSTATE_h, &pSrc->SFunction_DSTATE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_p);
   memcpy(&pDst->SFunction_DSTATE_p, &pSrc->SFunction_DSTATE_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_m);
   memcpy(&pDst->SFunction_DSTATE_m, &pSrc->SFunction_DSTATE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_lk);
   memcpy(&pDst->SFunction_DSTATE_lk, &pSrc->SFunction_DSTATE_lk, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_i);
   memcpy(&pDst->SFunction_DSTATE_i, &pSrc->SFunction_DSTATE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_ij);
   memcpy(&pDst->SFunction_DSTATE_ij, &pSrc->SFunction_DSTATE_ij, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_d);
   memcpy(&pDst->SFunction_DSTATE_d, &pSrc->SFunction_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_ow);
   memcpy(&pDst->SFunction_DSTATE_ow, &pSrc->SFunction_DSTATE_ow, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_it);
   memcpy(&pDst->SFunction_DSTATE_it, &pSrc->SFunction_DSTATE_it, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_pj);
   memcpy(&pDst->SFunction_DSTATE_pj, &pSrc->SFunction_DSTATE_pj, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_gx);
   memcpy(&pDst->SFunction_DSTATE_gx, &pSrc->SFunction_DSTATE_gx, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_k);
   memcpy(&pDst->SFunction_DSTATE_k, &pSrc->SFunction_DSTATE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_a);
   memcpy(&pDst->SFunction_DSTATE_a, &pSrc->SFunction_DSTATE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_li);
   memcpy(&pDst->SFunction_DSTATE_li, &pSrc->SFunction_DSTATE_li, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_pt);
   memcpy(&pDst->SFunction_DSTATE_pt, &pSrc->SFunction_DSTATE_pt, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_bl);
   memcpy(&pDst->SFunction_DSTATE_bl, &pSrc->SFunction_DSTATE_bl, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_bf);
   memcpy(&pDst->SFunction_DSTATE_bf, &pSrc->SFunction_DSTATE_bf, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9);
   memcpy(&pDst->MOV_segment9, &pSrc->MOV_segment9, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_c);
   memcpy(&pDst->MOV_segment9_c, &pSrc->MOV_segment9_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_e);
   memcpy(&pDst->MOV_segment9_e, &pSrc->MOV_segment9_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_b);
   memcpy(&pDst->MOV_segment9_b, &pSrc->MOV_segment9_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_f);
   memcpy(&pDst->MOV_segment9_f, &pSrc->MOV_segment9_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_m);
   memcpy(&pDst->MOV_segment9_m, &pSrc->MOV_segment9_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_a);
   memcpy(&pDst->MOV_segment9_a, &pSrc->MOV_segment9_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_n);
   memcpy(&pDst->MOV_segment9_n, &pSrc->MOV_segment9_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_a2);
   memcpy(&pDst->MOV_segment9_a2, &pSrc->MOV_segment9_a2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_i);
   memcpy(&pDst->MOV_segment9_i, &pSrc->MOV_segment9_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_h);
   memcpy(&pDst->UnitDelay_DSTATE_h, &pSrc->UnitDelay_DSTATE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_g);
   memcpy(&pDst->MOV_segment9_g, &pSrc->MOV_segment9_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_h);
   memcpy(&pDst->MOV_segment9_h, &pSrc->MOV_segment9_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_k);
   memcpy(&pDst->MOV_segment9_k, &pSrc->MOV_segment9_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_nm);
   memcpy(&pDst->MOV_segment9_nm, &pSrc->MOV_segment9_nm, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_kg);
   memcpy(&pDst->MOV_segment9_kg, &pSrc->MOV_segment9_kg, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_bm);
   memcpy(&pDst->MOV_segment9_bm, &pSrc->MOV_segment9_bm, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_md);
   memcpy(&pDst->MOV_segment9_md, &pSrc->MOV_segment9_md, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_cm);
   memcpy(&pDst->MOV_segment9_cm, &pSrc->MOV_segment9_cm, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_p);
   memcpy(&pDst->MOV_segment9_p, &pSrc->MOV_segment9_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_d);
   memcpy(&pDst->MOV_segment9_d, &pSrc->MOV_segment9_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_cd);
   memcpy(&pDst->MOV_segment9_cd, &pSrc->MOV_segment9_cd, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_ez);
   memcpy(&pDst->MOV_segment9_ez, &pSrc->MOV_segment9_ez, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_f0);
   memcpy(&pDst->MOV_segment9_f0, &pSrc->MOV_segment9_f0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_cf);
   memcpy(&pDst->MOV_segment9_cf, &pSrc->MOV_segment9_cf, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_ne);
   memcpy(&pDst->MOV_segment9_ne, &pSrc->MOV_segment9_ne, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_hs);
   memcpy(&pDst->MOV_segment9_hs, &pSrc->MOV_segment9_hs, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_kh);
   memcpy(&pDst->MOV_segment9_kh, &pSrc->MOV_segment9_kh, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_af);
   memcpy(&pDst->MOV_segment9_af, &pSrc->MOV_segment9_af, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_j);
   memcpy(&pDst->MOV_segment9_j, &pSrc->MOV_segment9_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_gz);
   memcpy(&pDst->MOV_segment9_gz, &pSrc->MOV_segment9_gz, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_dt);
   memcpy(&pDst->MOV_segment9_dt, &pSrc->MOV_segment9_dt, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_gw);
   memcpy(&pDst->MOV_segment9_gw, &pSrc->MOV_segment9_gw, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_l);
   memcpy(&pDst->MOV_segment9_l, &pSrc->MOV_segment9_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_co);
   memcpy(&pDst->MOV_segment9_co, &pSrc->MOV_segment9_co, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_pr);
   memcpy(&pDst->MOV_segment9_pr, &pSrc->MOV_segment9_pr, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_cy);
   memcpy(&pDst->MOV_segment9_cy, &pSrc->MOV_segment9_cy, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_fc);
   memcpy(&pDst->MOV_segment9_fc, &pSrc->MOV_segment9_fc, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_hz);
   memcpy(&pDst->MOV_segment9_hz, &pSrc->MOV_segment9_hz, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_pv);
   memcpy(&pDst->MOV_segment9_pv, &pSrc->MOV_segment9_pv, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_no);
   memcpy(&pDst->MOV_segment9_no, &pSrc->MOV_segment9_no, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_khb);
   memcpy(&pDst->MOV_segment9_khb, &pSrc->MOV_segment9_khb, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_ai);
   memcpy(&pDst->MOV_segment9_ai, &pSrc->MOV_segment9_ai, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_cw);
   memcpy(&pDst->MOV_segment9_cw, &pSrc->MOV_segment9_cw, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_ln);
   memcpy(&pDst->MOV_segment9_ln, &pSrc->MOV_segment9_ln, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_bt);
   memcpy(&pDst->MOV_segment9_bt, &pSrc->MOV_segment9_bt, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_hi);
   memcpy(&pDst->MOV_segment9_hi, &pSrc->MOV_segment9_hi, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_kk);
   memcpy(&pDst->MOV_segment9_kk, &pSrc->MOV_segment9_kk, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_du);
   memcpy(&pDst->MOV_segment9_du, &pSrc->MOV_segment9_du, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_hr);
   memcpy(&pDst->MOV_segment9_hr, &pSrc->MOV_segment9_hr, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_ig);
   memcpy(&pDst->MOV_segment9_ig, &pSrc->MOV_segment9_ig, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE);
   memcpy(&pDst->Integ4_DSTATE, &pSrc->Integ4_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_kd);
   memcpy(&pDst->UnitDelay_DSTATE_kd, &pSrc->UnitDelay_DSTATE_kd, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_c);
   memcpy(&pDst->UnitDelay1_DSTATE_c, &pSrc->UnitDelay1_DSTATE_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay2_DSTATE);
   memcpy(&pDst->UnitDelay2_DSTATE, &pSrc->UnitDelay2_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay3_DSTATE);
   memcpy(&pDst->UnitDelay3_DSTATE, &pSrc->UnitDelay3_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Delay_DSTATE_b);
   memcpy(&pDst->Delay_DSTATE_b, &pSrc->Delay_DSTATE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Delay1_DSTATE);
   memcpy(&pDst->Delay1_DSTATE, &pSrc->Delay1_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_n);
   memcpy(&pDst->Integ4_DSTATE_n, &pSrc->Integ4_DSTATE_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_d);
   memcpy(&pDst->UnitDelay_DSTATE_d, &pSrc->UnitDelay_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_pa);
   memcpy(&pDst->UnitDelay1_DSTATE_pa, &pSrc->UnitDelay1_DSTATE_pa, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_l);
   memcpy(&pDst->Integ4_DSTATE_l, &pSrc->Integ4_DSTATE_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_o);
   memcpy(&pDst->UnitDelay_DSTATE_o, &pSrc->UnitDelay_DSTATE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_pd);
   memcpy(&pDst->UnitDelay1_DSTATE_pd, &pSrc->UnitDelay1_DSTATE_pd, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay2_DSTATE_b);
   memcpy(&pDst->UnitDelay2_DSTATE_b, &pSrc->UnitDelay2_DSTATE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay3_DSTATE_e);
   memcpy(&pDst->UnitDelay3_DSTATE_e, &pSrc->UnitDelay3_DSTATE_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_c);
   memcpy(&pDst->Integ4_DSTATE_c, &pSrc->Integ4_DSTATE_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_h);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_h, &pSrc->DiscreteTimeIntegrator_DSTATE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_DSTATE);
   memcpy(&pDst->Integrator_DSTATE, &pSrc->Integrator_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Filter_DSTATE);
   memcpy(&pDst->Filter_DSTATE, &pSrc->Filter_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_oz);
   memcpy(&pDst->UnitDelay_DSTATE_oz, &pSrc->UnitDelay_DSTATE_oz, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_DSTATE_m);
   memcpy(&pDst->Integrator_DSTATE_m, &pSrc->Integrator_DSTATE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Filter_DSTATE_p);
   memcpy(&pDst->Filter_DSTATE_p, &pSrc->Filter_DSTATE_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_i);
   memcpy(&pDst->Integ4_DSTATE_i, &pSrc->Integ4_DSTATE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_d1);
   memcpy(&pDst->UnitDelay_DSTATE_d1, &pSrc->UnitDelay_DSTATE_d1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_o);
   memcpy(&pDst->UnitDelay1_DSTATE_o, &pSrc->UnitDelay1_DSTATE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteDerivative_states);
   memcpy(&pDst->DiscreteDerivative_states, &pSrc->DiscreteDerivative_states, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_b);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_b, &pSrc->DiscreteTimeIntegrator_DSTATE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Delay_x1_DSTATE);
   memcpy(&pDst->Delay_x1_DSTATE, &pSrc->Delay_x1_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Delay_x2_DSTATE);
   memcpy(&pDst->Delay_x2_DSTATE, &pSrc->Delay_x2_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_mc);
   memcpy(&pDst->SFunction_DSTATE_mc, &pSrc->SFunction_DSTATE_mc, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_lb);
   memcpy(&pDst->SFunction_DSTATE_lb, &pSrc->SFunction_DSTATE_lb, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_pa);
   memcpy(&pDst->MOV_segment9_pa, &pSrc->MOV_segment9_pa, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_o);
   memcpy(&pDst->MOV_segment9_o, &pSrc->MOV_segment9_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_kx);
   memcpy(&pDst->MOV_segment9_kx, &pSrc->MOV_segment9_kx, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_e2);
   memcpy(&pDst->MOV_segment9_e2, &pSrc->MOV_segment9_e2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_afl);
   memcpy(&pDst->MOV_segment9_afl, &pSrc->MOV_segment9_afl, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_ir);
   memcpy(&pDst->MOV_segment9_ir, &pSrc->MOV_segment9_ir, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_cq);
   memcpy(&pDst->MOV_segment9_cq, &pSrc->MOV_segment9_cq, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_bh);
   memcpy(&pDst->MOV_segment9_bh, &pSrc->MOV_segment9_bh, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_ex);
   memcpy(&pDst->MOV_segment9_ex, &pSrc->MOV_segment9_ex, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_li);
   memcpy(&pDst->MOV_segment9_li, &pSrc->MOV_segment9_li, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_f);
   memcpy(&pDst->SFunction_DSTATE_f, &pSrc->SFunction_DSTATE_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_e);
   memcpy(&pDst->SFunction_DSTATE_e, &pSrc->SFunction_DSTATE_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_lu);
   memcpy(&pDst->MOV_segment9_lu, &pSrc->MOV_segment9_lu, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_mk);
   memcpy(&pDst->MOV_segment9_mk, &pSrc->MOV_segment9_mk, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_cn);
   memcpy(&pDst->MOV_segment9_cn, &pSrc->MOV_segment9_cn, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_et);
   memcpy(&pDst->MOV_segment9_et, &pSrc->MOV_segment9_et, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_fi);
   memcpy(&pDst->MOV_segment9_fi, &pSrc->MOV_segment9_fi, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_dg);
   memcpy(&pDst->MOV_segment9_dg, &pSrc->MOV_segment9_dg, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_lh);
   memcpy(&pDst->MOV_segment9_lh, &pSrc->MOV_segment9_lh, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_je);
   memcpy(&pDst->MOV_segment9_je, &pSrc->MOV_segment9_je, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_e3);
   memcpy(&pDst->MOV_segment9_e3, &pSrc->MOV_segment9_e3, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_dd);
   memcpy(&pDst->MOV_segment9_dd, &pSrc->MOV_segment9_dd, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_he);
   memcpy(&pDst->SFunction_DSTATE_he, &pSrc->SFunction_DSTATE_he, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_DSTATE_au);
   memcpy(&pDst->SFunction_DSTATE_au, &pSrc->SFunction_DSTATE_au, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_bc);
   memcpy(&pDst->MOV_segment9_bc, &pSrc->MOV_segment9_bc, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_m0);
   memcpy(&pDst->MOV_segment9_m0, &pSrc->MOV_segment9_m0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_ed);
   memcpy(&pDst->MOV_segment9_ed, &pSrc->MOV_segment9_ed, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_dc);
   memcpy(&pDst->MOV_segment9_dc, &pSrc->MOV_segment9_dc, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_bi);
   memcpy(&pDst->MOV_segment9_bi, &pSrc->MOV_segment9_bi, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_dl);
   memcpy(&pDst->MOV_segment9_dl, &pSrc->MOV_segment9_dl, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_fb);
   memcpy(&pDst->MOV_segment9_fb, &pSrc->MOV_segment9_fb, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_aj);
   memcpy(&pDst->MOV_segment9_aj, &pSrc->MOV_segment9_aj, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_kl);
   memcpy(&pDst->MOV_segment9_kl, &pSrc->MOV_segment9_kl, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_g5);
   memcpy(&pDst->MOV_segment9_g5, &pSrc->MOV_segment9_g5, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_bj);
   memcpy(&pDst->MOV_segment9_bj, &pSrc->MOV_segment9_bj, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_fq);
   memcpy(&pDst->MOV_segment9_fq, &pSrc->MOV_segment9_fq, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_gf);
   memcpy(&pDst->MOV_segment9_gf, &pSrc->MOV_segment9_gf, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_ac);
   memcpy(&pDst->MOV_segment9_ac, &pSrc->MOV_segment9_ac, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_lh1);
   memcpy(&pDst->MOV_segment9_lh1, &pSrc->MOV_segment9_lh1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_bk);
   memcpy(&pDst->MOV_segment9_bk, &pSrc->MOV_segment9_bk, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_is);
   memcpy(&pDst->MOV_segment9_is, &pSrc->MOV_segment9_is, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_m2);
   memcpy(&pDst->MOV_segment9_m2, &pSrc->MOV_segment9_m2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_di);
   memcpy(&pDst->MOV_segment9_di, &pSrc->MOV_segment9_di, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_mt);
   memcpy(&pDst->MOV_segment9_mt, &pSrc->MOV_segment9_mt, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_j3);
   memcpy(&pDst->MOV_segment9_j3, &pSrc->MOV_segment9_j3, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_dz);
   memcpy(&pDst->MOV_segment9_dz, &pSrc->MOV_segment9_dz, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_le);
   memcpy(&pDst->MOV_segment9_le, &pSrc->MOV_segment9_le, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_p0);
   memcpy(&pDst->MOV_segment9_p0, &pSrc->MOV_segment9_p0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_eo);
   memcpy(&pDst->MOV_segment9_eo, &pSrc->MOV_segment9_eo, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_gb);
   memcpy(&pDst->MOV_segment9_gb, &pSrc->MOV_segment9_gb, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_bd);
   memcpy(&pDst->MOV_segment9_bd, &pSrc->MOV_segment9_bd, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_nw);
   memcpy(&pDst->MOV_segment9_nw, &pSrc->MOV_segment9_nw, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_l2);
   memcpy(&pDst->MOV_segment9_l2, &pSrc->MOV_segment9_l2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_mn);
   memcpy(&pDst->MOV_segment9_mn, &pSrc->MOV_segment9_mn, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_oc);
   memcpy(&pDst->MOV_segment9_oc, &pSrc->MOV_segment9_oc, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_py);
   memcpy(&pDst->MOV_segment9_py, &pSrc->MOV_segment9_py, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_gd);
   memcpy(&pDst->MOV_segment9_gd, &pSrc->MOV_segment9_gd, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_oa);
   memcpy(&pDst->MOV_segment9_oa, &pSrc->MOV_segment9_oa, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_bj0);
   memcpy(&pDst->MOV_segment9_bj0, &pSrc->MOV_segment9_bj0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_nd);
   memcpy(&pDst->MOV_segment9_nd, &pSrc->MOV_segment9_nd, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_js);
   memcpy(&pDst->MOV_segment9_js, &pSrc->MOV_segment9_js, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_hy);
   memcpy(&pDst->MOV_segment9_hy, &pSrc->MOV_segment9_hy, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_lj);
   memcpy(&pDst->MOV_segment9_lj, &pSrc->MOV_segment9_lj, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->MOV_segment9_kr);
   memcpy(&pDst->MOV_segment9_kr, &pSrc->MOV_segment9_kr, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_d);
   memcpy(&pDst->Integ4_DSTATE_d, &pSrc->Integ4_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_g);
   memcpy(&pDst->UnitDelay_DSTATE_g, &pSrc->UnitDelay_DSTATE_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_j);
   memcpy(&pDst->UnitDelay1_DSTATE_j, &pSrc->UnitDelay1_DSTATE_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_p);
   memcpy(&pDst->Integ4_DSTATE_p, &pSrc->Integ4_DSTATE_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_p);
   memcpy(&pDst->UnitDelay_DSTATE_p, &pSrc->UnitDelay_DSTATE_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_l);
   memcpy(&pDst->UnitDelay1_DSTATE_l, &pSrc->UnitDelay1_DSTATE_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_PreviousInput);
   memcpy(&pDst->SFunction_PreviousInput, &pSrc->SFunction_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->itinit1_PreviousInput);
   memcpy(&pDst->itinit1_PreviousInput, &pSrc->itinit1_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->itinit_PreviousInput);
   memcpy(&pDst->itinit_PreviousInput, &pSrc->itinit_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory2_PreviousInput);
   memcpy(&pDst->Memory2_PreviousInput, &pSrc->Memory2_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->PrevY);
   memcpy(&pDst->PrevY, &pSrc->PrevY, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput);
   memcpy(&pDst->Memory_PreviousInput, &pSrc->Memory_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_g);
   memcpy(&pDst->Memory_PreviousInput_g, &pSrc->Memory_PreviousInput_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory1_PreviousInput);
   memcpy(&pDst->Memory1_PreviousInput, &pSrc->Memory1_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_gb);
   memcpy(&pDst->Memory_PreviousInput_gb, &pSrc->Memory_PreviousInput_gb, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_o);
   memcpy(&pDst->Memory_PreviousInput_o, &pSrc->Memory_PreviousInput_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_o5);
   memcpy(&pDst->Memory_PreviousInput_o5, &pSrc->Memory_PreviousInput_o5, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_h);
   memcpy(&pDst->Memory_PreviousInput_h, &pSrc->Memory_PreviousInput_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_l);
   memcpy(&pDst->Memory_PreviousInput_l, &pSrc->Memory_PreviousInput_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA);
   memcpy(&pDst->TimeStampA, &pSrc->TimeStampA, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA);
   memcpy(&pDst->LastUAtTimeA, &pSrc->LastUAtTimeA, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB);
   memcpy(&pDst->TimeStampB, &pSrc->TimeStampB, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB);
   memcpy(&pDst->LastUAtTimeB, &pSrc->LastUAtTimeB, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_l);
   memcpy(&pDst->TimeStampA_l, &pSrc->TimeStampA_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_j);
   memcpy(&pDst->LastUAtTimeA_j, &pSrc->LastUAtTimeA_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_n);
   memcpy(&pDst->TimeStampB_n, &pSrc->TimeStampB_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_k);
   memcpy(&pDst->LastUAtTimeB_k, &pSrc->LastUAtTimeB_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_o);
   memcpy(&pDst->TimeStampA_o, &pSrc->TimeStampA_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_g);
   memcpy(&pDst->LastUAtTimeA_g, &pSrc->LastUAtTimeA_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_h);
   memcpy(&pDst->TimeStampB_h, &pSrc->TimeStampB_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_j);
   memcpy(&pDst->LastUAtTimeB_j, &pSrc->LastUAtTimeB_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_e);
   memcpy(&pDst->TimeStampA_e, &pSrc->TimeStampA_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_b);
   memcpy(&pDst->LastUAtTimeA_b, &pSrc->LastUAtTimeA_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_e);
   memcpy(&pDst->TimeStampB_e, &pSrc->TimeStampB_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_m);
   memcpy(&pDst->LastUAtTimeB_m, &pSrc->LastUAtTimeB_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_f);
   memcpy(&pDst->TimeStampA_f, &pSrc->TimeStampA_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_e);
   memcpy(&pDst->LastUAtTimeA_e, &pSrc->LastUAtTimeA_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_m);
   memcpy(&pDst->TimeStampB_m, &pSrc->TimeStampB_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_o);
   memcpy(&pDst->LastUAtTimeB_o, &pSrc->LastUAtTimeB_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_li);
   memcpy(&pDst->TimeStampA_li, &pSrc->TimeStampA_li, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_o);
   memcpy(&pDst->LastUAtTimeA_o, &pSrc->LastUAtTimeA_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_g);
   memcpy(&pDst->TimeStampB_g, &pSrc->TimeStampB_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_kv);
   memcpy(&pDst->LastUAtTimeB_kv, &pSrc->LastUAtTimeB_kv, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_d);
   memcpy(&pDst->TimeStampA_d, &pSrc->TimeStampA_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_a);
   memcpy(&pDst->LastUAtTimeA_a, &pSrc->LastUAtTimeA_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_mc);
   memcpy(&pDst->TimeStampB_mc, &pSrc->TimeStampB_mc, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_p);
   memcpy(&pDst->LastUAtTimeB_p, &pSrc->LastUAtTimeB_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_c);
   memcpy(&pDst->TimeStampA_c, &pSrc->TimeStampA_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_c);
   memcpy(&pDst->LastUAtTimeA_c, &pSrc->LastUAtTimeA_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_p);
   memcpy(&pDst->TimeStampB_p, &pSrc->TimeStampB_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_h);
   memcpy(&pDst->LastUAtTimeB_h, &pSrc->LastUAtTimeB_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_fi);
   memcpy(&pDst->TimeStampA_fi, &pSrc->TimeStampA_fi, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_p);
   memcpy(&pDst->LastUAtTimeA_p, &pSrc->LastUAtTimeA_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_gn);
   memcpy(&pDst->TimeStampB_gn, &pSrc->TimeStampB_gn, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_c);
   memcpy(&pDst->LastUAtTimeB_c, &pSrc->LastUAtTimeB_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_a);
   memcpy(&pDst->TimeStampA_a, &pSrc->TimeStampA_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_d);
   memcpy(&pDst->LastUAtTimeA_d, &pSrc->LastUAtTimeA_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_b);
   memcpy(&pDst->TimeStampB_b, &pSrc->TimeStampB_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_i);
   memcpy(&pDst->LastUAtTimeB_i, &pSrc->LastUAtTimeB_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_lh);
   memcpy(&pDst->TimeStampA_lh, &pSrc->TimeStampA_lh, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_os);
   memcpy(&pDst->LastUAtTimeA_os, &pSrc->LastUAtTimeA_os, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_k);
   memcpy(&pDst->TimeStampB_k, &pSrc->TimeStampB_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_ot);
   memcpy(&pDst->LastUAtTimeB_ot, &pSrc->LastUAtTimeB_ot, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_h);
   memcpy(&pDst->TimeStampA_h, &pSrc->TimeStampA_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_f);
   memcpy(&pDst->LastUAtTimeA_f, &pSrc->LastUAtTimeA_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_d);
   memcpy(&pDst->TimeStampB_d, &pSrc->TimeStampB_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_ig);
   memcpy(&pDst->LastUAtTimeB_ig, &pSrc->LastUAtTimeB_ig, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_dx);
   memcpy(&pDst->TimeStampA_dx, &pSrc->TimeStampA_dx, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_n);
   memcpy(&pDst->LastUAtTimeA_n, &pSrc->LastUAtTimeA_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_pv);
   memcpy(&pDst->TimeStampB_pv, &pSrc->TimeStampB_pv, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_n);
   memcpy(&pDst->LastUAtTimeB_n, &pSrc->LastUAtTimeB_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_k);
   memcpy(&pDst->TimeStampA_k, &pSrc->TimeStampA_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_nc);
   memcpy(&pDst->LastUAtTimeA_nc, &pSrc->LastUAtTimeA_nc, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_dg);
   memcpy(&pDst->TimeStampB_dg, &pSrc->TimeStampB_dg, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_d);
   memcpy(&pDst->LastUAtTimeB_d, &pSrc->LastUAtTimeB_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_j);
   memcpy(&pDst->TimeStampA_j, &pSrc->TimeStampA_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_h);
   memcpy(&pDst->LastUAtTimeA_h, &pSrc->LastUAtTimeA_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_a);
   memcpy(&pDst->TimeStampB_a, &pSrc->TimeStampB_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_ik);
   memcpy(&pDst->LastUAtTimeB_ik, &pSrc->LastUAtTimeB_ik, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_au);
   memcpy(&pDst->TimeStampA_au, &pSrc->TimeStampA_au, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_g3);
   memcpy(&pDst->LastUAtTimeA_g3, &pSrc->LastUAtTimeA_g3, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_g5);
   memcpy(&pDst->TimeStampB_g5, &pSrc->TimeStampB_g5, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_ml);
   memcpy(&pDst->LastUAtTimeB_ml, &pSrc->LastUAtTimeB_ml, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_fh);
   memcpy(&pDst->TimeStampA_fh, &pSrc->TimeStampA_fh, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_dl);
   memcpy(&pDst->LastUAtTimeA_dl, &pSrc->LastUAtTimeA_dl, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_kd);
   memcpy(&pDst->TimeStampB_kd, &pSrc->TimeStampB_kd, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_l);
   memcpy(&pDst->LastUAtTimeB_l, &pSrc->LastUAtTimeB_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_fo);
   memcpy(&pDst->TimeStampA_fo, &pSrc->TimeStampA_fo, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_g4);
   memcpy(&pDst->LastUAtTimeA_g4, &pSrc->LastUAtTimeA_g4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_aa);
   memcpy(&pDst->TimeStampB_aa, &pSrc->TimeStampB_aa, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_d2);
   memcpy(&pDst->LastUAtTimeB_d2, &pSrc->LastUAtTimeB_d2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_g);
   memcpy(&pDst->TimeStampA_g, &pSrc->TimeStampA_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_bj);
   memcpy(&pDst->LastUAtTimeA_bj, &pSrc->LastUAtTimeA_bj, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_g5h);
   memcpy(&pDst->TimeStampB_g5h, &pSrc->TimeStampB_g5h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_nw);
   memcpy(&pDst->LastUAtTimeB_nw, &pSrc->LastUAtTimeB_nw, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_ho);
   memcpy(&pDst->TimeStampA_ho, &pSrc->TimeStampA_ho, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_og);
   memcpy(&pDst->LastUAtTimeA_og, &pSrc->LastUAtTimeA_og, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_eu);
   memcpy(&pDst->TimeStampB_eu, &pSrc->TimeStampB_eu, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_a);
   memcpy(&pDst->LastUAtTimeB_a, &pSrc->LastUAtTimeB_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_gy);
   memcpy(&pDst->TimeStampA_gy, &pSrc->TimeStampA_gy, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_l);
   memcpy(&pDst->LastUAtTimeA_l, &pSrc->LastUAtTimeA_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_de);
   memcpy(&pDst->TimeStampB_de, &pSrc->TimeStampB_de, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_am);
   memcpy(&pDst->LastUAtTimeB_am, &pSrc->LastUAtTimeB_am, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_b);
   memcpy(&pDst->TimeStampA_b, &pSrc->TimeStampA_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_gf);
   memcpy(&pDst->LastUAtTimeA_gf, &pSrc->LastUAtTimeA_gf, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_f);
   memcpy(&pDst->TimeStampB_f, &pSrc->TimeStampB_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_b);
   memcpy(&pDst->LastUAtTimeB_b, &pSrc->LastUAtTimeB_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_h2);
   memcpy(&pDst->TimeStampA_h2, &pSrc->TimeStampA_h2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_ai);
   memcpy(&pDst->LastUAtTimeA_ai, &pSrc->LastUAtTimeA_ai, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_o);
   memcpy(&pDst->TimeStampB_o, &pSrc->TimeStampB_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_pk);
   memcpy(&pDst->LastUAtTimeB_pk, &pSrc->LastUAtTimeB_pk, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_a0);
   memcpy(&pDst->TimeStampA_a0, &pSrc->TimeStampA_a0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_od);
   memcpy(&pDst->LastUAtTimeA_od, &pSrc->LastUAtTimeA_od, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_pz);
   memcpy(&pDst->TimeStampB_pz, &pSrc->TimeStampB_pz, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_cf);
   memcpy(&pDst->LastUAtTimeB_cf, &pSrc->LastUAtTimeB_cf, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_bs);
   memcpy(&pDst->TimeStampA_bs, &pSrc->TimeStampA_bs, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_odu);
   memcpy(&pDst->LastUAtTimeA_odu, &pSrc->LastUAtTimeA_odu, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_l);
   memcpy(&pDst->TimeStampB_l, &pSrc->TimeStampB_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_nk);
   memcpy(&pDst->LastUAtTimeB_nk, &pSrc->LastUAtTimeB_nk, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampA_a2);
   memcpy(&pDst->TimeStampA_a2, &pSrc->TimeStampA_a2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeA_bc);
   memcpy(&pDst->LastUAtTimeA_bc, &pSrc->LastUAtTimeA_bc, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TimeStampB_bg);
   memcpy(&pDst->TimeStampB_bg, &pSrc->TimeStampB_bg, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LastUAtTimeB_hw);
   memcpy(&pDst->LastUAtTimeB_hw, &pSrc->LastUAtTimeB_hw, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_go);
   memcpy(&pDst->Memory_PreviousInput_go, &pSrc->Memory_PreviousInput_go, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_n);
   memcpy(&pDst->Memory_PreviousInput_n, &pSrc->Memory_PreviousInput_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory1_PreviousInput_p);
   memcpy(&pDst->Memory1_PreviousInput_p, &pSrc->Memory1_PreviousInput_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteDerivative_tmp);
   memcpy(&pDst->DiscreteDerivative_tmp, &pSrc->DiscreteDerivative_tmp, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->PrevY_e);
   memcpy(&pDst->PrevY_e, &pSrc->PrevY_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->VariableTimeDelay_RWORK);
   memcpy(&pDst->VariableTimeDelay_RWORK, &pSrc->VariableTimeDelay_RWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK);
   memcpy(&pDst->SFunction_RWORK, &pSrc->SFunction_RWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_RWORK);
   memcpy(&pDst->TransportDelay_RWORK, &pSrc->TransportDelay_RWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_l);
   memcpy(&pDst->SFunction_RWORK_l, &pSrc->SFunction_RWORK_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_n);
   memcpy(&pDst->SFunction_RWORK_n, &pSrc->SFunction_RWORK_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_p);
   memcpy(&pDst->SFunction_RWORK_p, &pSrc->SFunction_RWORK_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_j);
   memcpy(&pDst->SFunction_RWORK_j, &pSrc->SFunction_RWORK_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_e);
   memcpy(&pDst->SFunction_RWORK_e, &pSrc->SFunction_RWORK_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_jd);
   memcpy(&pDst->SFunction_RWORK_jd, &pSrc->SFunction_RWORK_jd, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->VariableTimeDelay_IWORK);
   memcpy(&pDst->VariableTimeDelay_IWORK, &pSrc->VariableTimeDelay_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK);
   memcpy(&pDst->SFunction_IWORK, &pSrc->SFunction_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_b);
   memcpy(&pDst->SFunction_IWORK_b, &pSrc->SFunction_IWORK_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_m);
   memcpy(&pDst->SFunction_IWORK_m, &pSrc->SFunction_IWORK_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_e);
   memcpy(&pDst->SFunction_IWORK_e, &pSrc->SFunction_IWORK_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_c);
   memcpy(&pDst->SFunction_IWORK_c, &pSrc->SFunction_IWORK_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_n);
   memcpy(&pDst->SFunction_IWORK_n, &pSrc->SFunction_IWORK_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_f);
   memcpy(&pDst->SFunction_IWORK_f, &pSrc->SFunction_IWORK_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_ev);
   memcpy(&pDst->SFunction_IWORK_ev, &pSrc->SFunction_IWORK_ev, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_ce);
   memcpy(&pDst->SFunction_IWORK_ce, &pSrc->SFunction_IWORK_ce, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_i);
   memcpy(&pDst->SFunction_IWORK_i, &pSrc->SFunction_IWORK_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_l);
   memcpy(&pDst->SFunction_IWORK_l, &pSrc->SFunction_IWORK_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_k);
   memcpy(&pDst->SFunction_IWORK_k, &pSrc->SFunction_IWORK_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_o);
   memcpy(&pDst->SFunction_IWORK_o, &pSrc->SFunction_IWORK_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_h);
   memcpy(&pDst->SFunction_IWORK_h, &pSrc->SFunction_IWORK_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_g);
   memcpy(&pDst->SFunction_IWORK_g, &pSrc->SFunction_IWORK_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_eo);
   memcpy(&pDst->SFunction_IWORK_eo, &pSrc->SFunction_IWORK_eo, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_a);
   memcpy(&pDst->SFunction_IWORK_a, &pSrc->SFunction_IWORK_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_lo);
   memcpy(&pDst->SFunction_IWORK_lo, &pSrc->SFunction_IWORK_lo, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_fr);
   memcpy(&pDst->SFunction_IWORK_fr, &pSrc->SFunction_IWORK_fr, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_nz);
   memcpy(&pDst->SFunction_IWORK_nz, &pSrc->SFunction_IWORK_nz, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_d);
   memcpy(&pDst->SFunction_IWORK_d, &pSrc->SFunction_IWORK_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_IWORK);
   memcpy(&pDst->TransportDelay_IWORK, &pSrc->TransportDelay_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_ol);
   memcpy(&pDst->SFunction_IWORK_ol, &pSrc->SFunction_IWORK_ol, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_bb);
   memcpy(&pDst->SFunction_IWORK_bb, &pSrc->SFunction_IWORK_bb, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_oo);
   memcpy(&pDst->SFunction_IWORK_oo, &pSrc->SFunction_IWORK_oo, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_it);
   memcpy(&pDst->SFunction_IWORK_it, &pSrc->SFunction_IWORK_it, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_o0);
   memcpy(&pDst->SFunction_IWORK_o0, &pSrc->SFunction_IWORK_o0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_hv);
   memcpy(&pDst->SFunction_IWORK_hv, &pSrc->SFunction_IWORK_hv, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_ml);
   memcpy(&pDst->SFunction_IWORK_ml, &pSrc->SFunction_IWORK_ml, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_il);
   memcpy(&pDst->SFunction_IWORK_il, &pSrc->SFunction_IWORK_il, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->inti_PrevResetState);
   memcpy(&pDst->inti_PrevResetState, &pSrc->inti_PrevResetState, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_PrevRese);
   memcpy(&pDst->DiscreteTimeIntegrator_PrevRese, &pSrc->DiscreteTimeIntegrator_PrevRese, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->inti_IC_LOADING);
   memcpy(&pDst->inti_IC_LOADING, &pSrc->inti_IC_LOADING, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE, &pSrc->Integ4_SYSTEM_ENABLE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_n);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_n, &pSrc->Integ4_SYSTEM_ENABLE_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_j);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_j, &pSrc->Integ4_SYSTEM_ENABLE_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_l);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_l, &pSrc->Integ4_SYSTEM_ENABLE_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_m);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_m, &pSrc->Integ4_SYSTEM_ENABLE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_h);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_h, &pSrc->Integ4_SYSTEM_ENABLE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_f);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_f, &pSrc->Integ4_SYSTEM_ENABLE_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Initial_FirstOutputTime);
   memcpy(&pDst->Initial_FirstOutputTime, &pSrc->Initial_FirstOutputTime, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->AutomaticGainControl_MODE);
   memcpy(&pDst->AutomaticGainControl_MODE, &pSrc->AutomaticGainControl_MODE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Signalgenerator_j);
   memcpy(&pDst->Signalgenerator_j, &pSrc->Signalgenerator_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->HarmonicGenerator_g);
   memcpy(&pDst->HarmonicGenerator_g, &pSrc->HarmonicGenerator_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Signalgenerator);
   memcpy(&pDst->Signalgenerator, &pSrc->Signalgenerator, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->HarmonicGenerator);
   memcpy(&pDst->HarmonicGenerator, &pSrc->HarmonicGenerator, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_f);
   memcpy(&pDst->TrueRMS_f, &pSrc->TrueRMS_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_ng);
   memcpy(&pDst->RMS_ng, &pSrc->RMS_ng, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_ml);
   memcpy(&pDst->TrueRMS_ml, &pSrc->TrueRMS_ml, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_my);
   memcpy(&pDst->RMS_my, &pSrc->RMS_my, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_j2);
   memcpy(&pDst->TrueRMS_j2, &pSrc->TrueRMS_j2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_hk);
   memcpy(&pDst->RMS_hk, &pSrc->RMS_hk, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_ik);
   memcpy(&pDst->TrueRMS_ik, &pSrc->TrueRMS_ik, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_k);
   memcpy(&pDst->RMS_k, &pSrc->RMS_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_jr);
   memcpy(&pDst->TrueRMS_jr, &pSrc->TrueRMS_jr, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_bz);
   memcpy(&pDst->RMS_bz, &pSrc->RMS_bz, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_dt);
   memcpy(&pDst->TrueRMS_dt, &pSrc->TrueRMS_dt, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_pj);
   memcpy(&pDst->RMS_pj, &pSrc->RMS_pj, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_mi);
   memcpy(&pDst->TrueRMS_mi, &pSrc->TrueRMS_mi, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_jo);
   memcpy(&pDst->RMS_jo, &pSrc->RMS_jo, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_c0);
   memcpy(&pDst->TrueRMS_c0, &pSrc->TrueRMS_c0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_a);
   memcpy(&pDst->RMS_a, &pSrc->RMS_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_kx);
   memcpy(&pDst->TrueRMS_kx, &pSrc->TrueRMS_kx, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_b4);
   memcpy(&pDst->RMS_b4, &pSrc->RMS_b4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_k);
   memcpy(&pDst->TrueRMS_k, &pSrc->TrueRMS_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_bh);
   memcpy(&pDst->RMS_bh, &pSrc->RMS_bh, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_gs);
   memcpy(&pDst->TrueRMS_gs, &pSrc->TrueRMS_gs, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_cb);
   memcpy(&pDst->RMS_cb, &pSrc->RMS_cb, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_h);
   memcpy(&pDst->TrueRMS_h, &pSrc->TrueRMS_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_cc);
   memcpy(&pDst->RMS_cc, &pSrc->RMS_cc, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_ay);
   memcpy(&pDst->TrueRMS_ay, &pSrc->TrueRMS_ay, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_p2);
   memcpy(&pDst->RMS_p2, &pSrc->RMS_p2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_g);
   memcpy(&pDst->TrueRMS_g, &pSrc->TrueRMS_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_h);
   memcpy(&pDst->RMS_h, &pSrc->RMS_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_dq);
   memcpy(&pDst->TrueRMS_dq, &pSrc->TrueRMS_dq, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_mf);
   memcpy(&pDst->RMS_mf, &pSrc->RMS_mf, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_dw);
   memcpy(&pDst->TrueRMS_dw, &pSrc->TrueRMS_dw, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_j2);
   memcpy(&pDst->RMS_j2, &pSrc->RMS_j2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_b);
   memcpy(&pDst->TrueRMS_b, &pSrc->TrueRMS_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_o);
   memcpy(&pDst->RMS_o, &pSrc->RMS_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_ae);
   memcpy(&pDst->TrueRMS_ae, &pSrc->TrueRMS_ae, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_j);
   memcpy(&pDst->RMS_j, &pSrc->RMS_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_m);
   memcpy(&pDst->TrueRMS_m, &pSrc->TrueRMS_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_l);
   memcpy(&pDst->RMS_l, &pSrc->RMS_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_c);
   memcpy(&pDst->TrueRMS_c, &pSrc->TrueRMS_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_n);
   memcpy(&pDst->RMS_n, &pSrc->RMS_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_ad);
   memcpy(&pDst->TrueRMS_ad, &pSrc->TrueRMS_ad, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_b);
   memcpy(&pDst->RMS_b, &pSrc->RMS_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_an);
   memcpy(&pDst->TrueRMS_an, &pSrc->TrueRMS_an, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_p);
   memcpy(&pDst->RMS_p, &pSrc->RMS_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_e);
   memcpy(&pDst->TrueRMS_e, &pSrc->TrueRMS_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_cw);
   memcpy(&pDst->RMS_cw, &pSrc->RMS_cw, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_i);
   memcpy(&pDst->TrueRMS_i, &pSrc->TrueRMS_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_c);
   memcpy(&pDst->RMS_c, &pSrc->RMS_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_d);
   memcpy(&pDst->TrueRMS_d, &pSrc->TrueRMS_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_m);
   memcpy(&pDst->RMS_m, &pSrc->RMS_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_a);
   memcpy(&pDst->TrueRMS_a, &pSrc->TrueRMS_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_id);
   memcpy(&pDst->RMS_id, &pSrc->RMS_id, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_j);
   memcpy(&pDst->TrueRMS_j, &pSrc->TrueRMS_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_il);
   memcpy(&pDst->RMS_il, &pSrc->RMS_il, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_p);
   memcpy(&pDst->TrueRMS_p, &pSrc->TrueRMS_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_i);
   memcpy(&pDst->RMS_i, &pSrc->RMS_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS);
   memcpy(&pDst->TrueRMS, &pSrc->TrueRMS, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS);
   memcpy(&pDst->RMS, &pSrc->RMS, eltSize);
   size += eltSize;

   return size;
}

/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from a raw buffer (src) 
 * to an RT_MODEL structure(dst), ignoring pointers.
 * Note that sub-structures are copied in one operation since they cannot contain pointers.
 */
int OpalSnapshot_Copy_TimingData(void * src, void * dst) {
   RT_MODEL	tmpBuffer;
   RT_MODEL * pSrc = &tmpBuffer;
   RT_MODEL * pDst = (RT_MODEL *)dst;
   int TimingSize = sizeof(tmpBuffer.Timing);
   int size = 0, eltSize = 0;

   memcpy(&tmpBuffer.Timing, src, TimingSize);

   eltSize = sizeof(pSrc->Timing.clockTick0);
   memcpy(&pDst->Timing.clockTick0, &pSrc->Timing.clockTick0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTick1);
   memcpy(&pDst->Timing.clockTick1, &pSrc->Timing.clockTick1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTick2);
   memcpy(&pDst->Timing.clockTick2, &pSrc->Timing.clockTick2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTickH0);
   memcpy(&pDst->Timing.clockTickH0, &pSrc->Timing.clockTickH0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTickH1);
   memcpy(&pDst->Timing.clockTickH1, &pSrc->Timing.clockTickH1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTickH2);
   memcpy(&pDst->Timing.clockTickH2, &pSrc->Timing.clockTickH2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tFinal);
   memcpy(&pDst->Timing.tFinal, &pSrc->Timing.tFinal, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.offsetTimesArray);
   memcpy(&pDst->Timing.offsetTimesArray, &pSrc->Timing.offsetTimesArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.perTaskSampleHitsArray);
   memcpy(&pDst->Timing.perTaskSampleHitsArray, &pSrc->Timing.perTaskSampleHitsArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleHitArray);
   memcpy(&pDst->Timing.sampleHitArray, &pSrc->Timing.sampleHitArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleTimesArray);
   memcpy(&pDst->Timing.sampleTimesArray, &pSrc->Timing.sampleTimesArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleTimeTaskIDArray);
   memcpy(&pDst->Timing.sampleTimeTaskIDArray, &pSrc->Timing.sampleTimeTaskIDArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.simTimeStep);
   memcpy(&pDst->Timing.simTimeStep, &pSrc->Timing.simTimeStep, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tStart);
   memcpy(&pDst->Timing.tStart, &pSrc->Timing.tStart, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize);
   memcpy(&pDst->Timing.stepSize, &pSrc->Timing.stepSize, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize0);
   memcpy(&pDst->Timing.stepSize0, &pSrc->Timing.stepSize0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize1);
   memcpy(&pDst->Timing.stepSize1, &pSrc->Timing.stepSize1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize2);
   memcpy(&pDst->Timing.stepSize2, &pSrc->Timing.stepSize2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stopRequestedFlag);
   memcpy(&pDst->Timing.stopRequestedFlag, &pSrc->Timing.stopRequestedFlag, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.TaskCounters);
   memcpy(&pDst->Timing.TaskCounters, &pSrc->Timing.TaskCounters, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tArray);
   memcpy(&pDst->Timing.tArray, &pSrc->Timing.tArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.timeOfLastOutput);
   memcpy(&pDst->Timing.timeOfLastOutput, &pSrc->Timing.timeOfLastOutput, eltSize);
   size += eltSize;

   return size;
}

/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from a raw buffer (src) 
 * to an RT_MODEL structure(dst), ignoring pointers.
 * Note that ingData must not be copied since it contains pointers.
 */
int OpalSnapshot_Copy_ModelData(void * src, void * dst) {
   RT_MODEL	tmpBuffer;
   RT_MODEL * pSrc = &tmpBuffer;
   RT_MODEL * pDst = (RT_MODEL *)dst;
   int ModelDataSize = sizeof(tmpBuffer.ModelData);
   int size = 0, eltSize = 0;

   memcpy(&tmpBuffer.ModelData, src, ModelDataSize);

   eltSize = sizeof(pSrc->ModelData.CTOutputIncnstWithState);
   memcpy(&pDst->ModelData.CTOutputIncnstWithState, &pSrc->ModelData.CTOutputIncnstWithState, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.derivCacheNeedsReset);
   memcpy(&pDst->ModelData.derivCacheNeedsReset, &pSrc->ModelData.derivCacheNeedsReset, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.OdeDeltaY);
   memcpy(&pDst->ModelData.OdeDeltaY, &pSrc->ModelData.OdeDeltaY, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.odeF);
   memcpy(&pDst->ModelData.odeF, &pSrc->ModelData.odeF, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.odeX0);
   memcpy(&pDst->ModelData.odeX0, &pSrc->ModelData.odeX0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.zCCacheNeedsReset);
   memcpy(&pDst->ModelData.zCCacheNeedsReset, &pSrc->ModelData.zCCacheNeedsReset, eltSize);
   size += eltSize;

   return size;
}

